Switched base image for one with ssm installed

diff --git a/assets/ssm.yaml b/assets/ssm.yaml
--- a/assets/ssm.yaml
+++ b/assets/ssm.yaml
@@ -9,6 +9,23 @@ phases:
         inputs:
           commands:
             - echo 'Start of the build phase.'
+      - name: OperatingSystemId
+        action: ExecuteBash
+        inputs:
+          commands:
+            - |
+              FILE=/etc/os-release
+              if [ -e $FILE ]; then
+                . $FILE
+                echo $ID
+              elif [ -f /etc/centos-release ]; then
+                echo centos
+              elif [ -f /etc/redhat-release ]; then
+                echo rhel
+              else
+                echo "Unable to identify the operating system. Failing build."
+                exit 1
+              fi
       - name: InstallSSMAgent
         action: ExecuteBash
         inputs:
@@ -25,6 +42,29 @@ phases:
         inputs:
           commands:
             - echo 'Start of the the validate phase.'
+      - name: GetJavaInstallPath
+        action: ExecuteBash
+        inputs:
+          commands:
+            - |
+              RELEASE='{{build.OperatingSystemId.outputs.stdout}}'
+              case "$RELEASE" in
+                'amzn')
+                  ARCH=`/usr/bin/arch`
+                  echo "/usr/lib/jvm/java-17-amazon-corretto.$ARCH/bin/java"
+                  ;;
+                *)
+                  echo /usr/lib/jvm/java-17-amazon-corretto/bin/java
+                  ;;
+              esac
+      - name: ValidateInstallationJava
+        action: Assert
+        inputs:
+          fileExists: '{{validate.GetJavaInstallPath.outputs.stdout}}'
+      - name: ValidateInstallationJavac
+        action: Assert
+        inputs:
+          fileExists: '{{validate.GetJavaInstallPath.outputs.stdout}}c'
   - name: test
     steps:
       - name: HelloWorldStep
